name: Run Script on Remote Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Run script on remote server
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes yang@yangli-feasibility.com  << 'EOF'
        echo "Hello, remote server!"
        /home/yang/update_lfd.sh
        EOF
